    
# .github/workflows/lint.yml

name: Go Linter

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version-file: go.mod
          cache: true # Caches Go modules for faster builds.

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0
          args: --verbose --enable=govet,nilnil

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run nil panic checks
        uses: qbaware/nilaway-action@v0.0.13
        with:
           package-to-scan: ./...


  